# Generated by Django 4.2.9 on 2024-04-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=500, verbose_name='Contact Email')),
                ('pay_rate', models.CharField(max_length=500, verbose_name='Contact Email')),
                ('is_active', models.BooleanField(default=False)),
                ('dateMade', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
