# Generated by Django 4.2.9 on 2024-04-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobBoard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_active',
            new_name='is_visible',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=500, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pay_rate',
            field=models.CharField(max_length=500, verbose_name='Pay Rate'),
        ),
    ]
