# Generated by Django 4.2 on 2024-04-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobBoard_app', '0003_alter_post_options_client_post_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='tools',
            field=models.CharField(blank=True, choices=[('Lawn Mower', 'LAWN MOWER'), ('Shovel', 'SHOVEL')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=200, verbose_name='Job Description'),
        ),
    ]
