# Generated by Django 4.2 on 2024-04-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobBoard_app', '0004_post_description_post_tools_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=200, verbose_name='Job Description'),
        ),
    ]
