# Generated by Django 4.2 on 2024-04-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobBoard_app', '0007_alter_post_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tools',
            field=models.CharField(blank=True, choices=[('Lawn Mower', 'LAWN MOWER'), ('shovel', 'SHOVEL'), ('Rake', 'RAKE')], max_length=200),
        ),
    ]
